const AppActionTypes = {
  SET_COORDINATES: "SET_COORDINATES",
  SET_CITY_STATE: "SET_CITY_STATE",
  GET_CURRENT_WEATHER_DATA: "GET_CURRENT_WEATHER_DATA",
  SET_LOCAL_DATE_TIME: "SET_LOCAL_DATE_TIME",
  TOGGLE_GEOLOCATION_ENABLED: "TOGGLE_GEOLOCATION_ENABLED"
};

export default AppActionTypes;
