const AppActionTypes = {
  SET_COORDINATES: "SET_COORDINATES",
  SET_CITY_STATE: "SET_CITY_STATE",
  SET_LOCAL_DATE_TIME: "SET_LOCAL_DATE_TIME",
  SET_WEATHER_STATUS: "SET_WEATHER_STATUS",
  SET_WEATHER_FORECAST: "SET_WEATHER_FORECAST",
  GET_CURRENT_WEATHER_DATA: "GET_CURRENT_WEATHER_DATA",
  TOGGLE_GEOLOCATION_ENABLED: "TOGGLE_GEOLOCATION_ENABLED"
};

export default AppActionTypes;
